#!/bin/bash

DIR="$( cd "$( dirname "$0" )" && pwd )"

while getopts ":dl" opt; do
  case $opt in
    l)
      echo "Running punk_fuzz in local mode... This should only be used for testing."

      cd $DIR

      #run crawl to generate urls to fuzz
      cd ..
      python punkcrawler.py
      cd $DIR

      python punk_mapreduce.py < urls_to_fuzz > output_local
      ;;

    d)
      echo "Running punk_fuzz in distributed mode."

      cd $DIR

      #run crawl to generate urls to fuzz
      cd ..
      python punkcrawler.py
      cd $DIR

      python punk_mapreduce.py -r hadoop --file pysolr/pysolr.py --file pysolr/BeautifulSoup.py --file mapreduce_indexer/mapreduce_indexer.py --file punk_fuzz.py\
 --file fuzzer_config/fuzz_config_parser.py --file fuzzer_config/punk_fuzz.cfg.xml\
 --python-archive includes.tar.gz < urls_to_fuzz > output_distributed
      ;;

   \?)
      echo "Invalid option: -$OPTARG. Use either -d (distributed mode) or -l (local mode)" >&2
      ;;

  esac
done
