#!/bin/bash

mkdir $HOME/tor9055
mkdir $HOME/tor9066
SCRIPT=`readlink -f $0`
# Absolute path this script is in, thus /home/user/bin
BASEDIR=`dirname $SCRIPT`
echo $BASEDIR

echo "Starting tor main/default and two others"
echo "Preparing to start tor as $CURRENT_USER..."
tor -f $BASEDIR/tor-files/torrc >> log/tor.log &
tor -f $BASEDIR/tor-files/torrc-9055 >> log/tor.log &
tor -f $BASEDIR/tor-files/torrc-9066 >> log/tor.log &
